### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by lbibass** [openglonmetal/MGL#7]
Trying to build on my Mac, M1 Max, Monterey 12.1. 

I keep getting the error

```In file included from MGL/src/buffers.c:26:
MGL/include/glm_context.h:152:5: error: unknown type name 'uint'; did you mean 'int'?

```
When using xcodebuild, it succeeds, but I'm not sure it should. 

```error: unable to spawn process '/usr/bin/make' (No such file or directory) (in target 'SPIRV-Headers' from project 'MGL')```

**Comment by darkaegisagain** [comment]
uint should work, I will change it to unsigned int which should conform to
M1. I know it works with Xcode on 12.4e with Intel.

Mike


"*The* difference between communism and *socialism* is that under
*socialism* central planning *ends* with *a* *gun* in your face, whereas
under communism central planning begins with a *gun* in your face." ― Kevin
D. Williamson

**Comment by lbibass** [comment]
MGL/src/framebuffers.c:32:13: error: conflicting types for 'createTextureLevel'
extern void createTextureLevel(GLMContext ctx, Texture *tex, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);

Got a new problem here.

**Comment by darkaegisagain** [comment]
I found that today, fixing framebuffers (depth attachments)... I just
copied the correct def to glm_context.h and deleted it from framebuffers.c

I can't see how this compiled on my local machine...

MIke

"*The* difference between communism and *socialism* is that under
*socialism* central planning *ends* with *a* *gun* in your face, whereas
under communism central planning begins with a *gun* in your face." ― Kevin
D. Williamson

**Comment by darkaegisagain** [comment]
Fixed, checked in a copy of frame buffer.c with the local def removed.
